name: Acquire License File

on:
  workflow_dispatch:

jobs:
  generate-alf:
    name: Generate ALF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request License File
        uses: game-ci/unity-builder@v4
        id: get-alf
        with:
          targetPlatform: WebGL
          unityVersion: auto
          customParameters: -quit -batchmode -createManualActivationFile

      - name: Upload ALF File
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: manualActivationFile.alf
