name: Build Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build for WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: "f1-4320-1111-1111-1111"
        with:
          targetPlatform: WebGL
