name: Get License ALF

on:
  workflow_dispatch:

jobs:
  generate-alf:
    runs-on: ubuntu-latest
    steps:
      - name: Create ALF File
        run: |
          mkdir -p .alf
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><LicenseRequest><DeveloperData Value=\"\"/><ClientData Value=\"\"/></LicenseRequest>" > .alf/Unity_v2022.x.alf

      - name: Upload ALF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: manual-activation-file
          path: .alf/
